pod 'Firebase/Core'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'todoApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for todoApp

  target 'todoApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'todoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'todoApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for todoApp-tvOS

  target 'todoApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
